name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Sync files to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          scp -o StrictHostKeyChecking=no -r * $EC2_USER@$EC2_PUBLIC_IP:/home/ubuntu/Django_coffeeshop

      - name: SSH to EC2 and Deploy
        env:
            EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
            EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
            cd /home/ubuntu/Django_coffeeshop
            python3 -m venv venv
            /home/ubuntu/Django_coffeeshop/venv/bin/python -m pip install --upgrade pip
            /home/ubuntu/Django_coffeeshop/venv/bin/pip install -r requirements.txt
            /home/ubuntu/Django_coffeeshop/venv/bin/python manage.py collectstatic --noinput
            /home/ubuntu/Django_coffeeshop/venv/bin/python manage.py migrate
            # sudo systemctl restart gunicorn
            # sudo systemctl restart nginx
          EOF
        